spring.application.name=libraryhub-borrow-service

spring.datasource.url=jdbc:mysql://localhost:3306/borrowrequestandapprovalservice
spring.datasource.username=root
spring.datasource.password=3303

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false