spring.application.name=Libraryhub_LibrarianService

spring.datasource.url=jdbc:mysql://localhost:3306/librarianservice
spring.datasource.username=root
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080